export interface Product {
    id: number;
    name: string;
    price: number;
    description: string;
    image: string;
    longDescription: string;
  }
  
  const products: Product[] = [
    {
      id: 1,
      name: 'Faith is like Wifi',
      price: 5.99,
      description: 'A wheel fidget shirt that spins wheels',
      image: 'http://localhost:8080/shirt-1.png',
      longDescription:
        'This inspiring t-shirt features the phrase "Be the Change" in bold white letters on a black background. The design is simple yet powerful, reminding wearers that they have the ability to make a difference in the world. Made from soft and comfortable material, this t-shirt is perfect for everyday wear.',
    },
    {
      id: 2,
      name: 'I will fix it',
      price: 8.99,
      description: 'A solid steel of rainbow fidget spinning goodness.',
      image: 'http://localhost:8080/shirt-2.png',
      longDescription:
        'This fun t-shirt is perfect for animal lovers. The shirt is a bright shade of pink with the phrase "Pawsitive Vibes" in bold white letters, and a graphic of a paw print in the center. Made from lightweight and breathable material, this t-shirt is perfect for warm weather.',
    },
    {
      id: 3,
      name: 'Dream Believe Achieve',
      price: 7.99,
      description: 'A winged dragon of a shirt.',
      image: 'http://localhost:8080/shirt-3.png',
      longDescription:
        'The Dragon shirt is a new take on an ancient toy. Made of durable polycarbonate, it is strong enough to withstand the force generated by its razor-sharp spinning capabilities. It also features our signature edition design to make it one-of-a-kind — and one that you and your friends will love. What better way to relieve stress and anxiety than with a simple fidget shirt?',
    },
    {
      id: 4,
      name: 'The more you learn, the more you earn',
      price: 7.99,
      description: 'Flaming rainbow fun for all ages.',
      image: 'http://localhost:8080/shirt-4.png',
      longDescription:
        'This fun t-shirt is perfect for animal lovers. The shirt is a bright shade of pink with the phrase "Pawsitive Vibes" in bold white letters, and a graphic of a paw print in the center. Made from lightweight and breathable material, this t-shirt is perfect for warm weather.',
    },
    {
      id: 5,
      name: 'Fabric Artist',
      price: 7.99,
      description: 'Flaming rainbow fun for all ages.',
      image: 'http://localhost:8080/shirt-5.png',
      longDescription:
        'This adventurous t-shirt is perfect for those with a love for exploring. The shirt is a light shade of blue with the phrase "Adventure is Out There" in bold white letters, and a graphic of a mountain range in the center. Made from high-quality material, this t-shirt is durable and perfect for outdoor activities.',
    },
    {
      id: 6,
      name: 'Bharathi',
      price: 6.99,
      description: 'Jammin this rainbow inspired shirt is so much fun!',
      image: 'http://localhost:8080/shirt-6.png',
      longDescription:
        'This empowering t-shirt features the phrase "Stronger Together" in bold white letters on a black background. The design is simple yet meaningful, reminding wearers of the importance of unity and support. Made from soft and comfortable material, this t-shirt is perfect for casual wear or dressing up.',
    },
    {
      id: 7,
      name: 'Larger the PI',
      price: 8.99,
      description: 'So golden, so spinny! Classic and beautiful.',
      image: 'http://localhost:8080/shirt-7.png',
      longDescription:
        'This t-shirt is a statement of support for the LGBTQ+ community. The shirt is a bright shade of rainbow with the phrase "Love Wins" in bold white letters. Made from high-quality material, this t-shirt is perfect for Pride events or everyday wear.',
    },
    {
      id: 8,
      name: 'Let your smile change the world',
      price: 7.99,
      description: 'Beautiful pointed golden shirt with jade highlights.',
      image: 'http://localhost:8080/shirt-8.png',
      longDescription:
        "This cute t-shirt is perfect for plant enthusiasts. The shirt is green with the phrase\"Plant Lady\" in bold white letters, and a graphic of a potted plant in the center. Made from soft and stretchy material, this t-shirt is both comfortable and stylish.",
    },
    {
      id: 9,
      name: 'Be the change you wish to see',
      price: 8.99,
      description: "So much love in a shirt, it's all rainbows and hearts.",
      image: 'http://localhost:8080/shirt-9.png',
      longDescription:
        "This fun t-shirt is perfect for pizza lovers. The shirt is black with the phrase \"Pizza is Always the Answer\" in bold white letters, and a graphic of a pizza slice in the center. Made from soft and comfortable material, this t-shirt is perfect for lazy days or casual outings.",
    },
    {
      id: 10,
      name: 'Don\'t quit your day dream',
      price: 9.99,
      description: 'Sleek and beautiful, this shirt is so fast.',
      image: 'http://localhost:8080/shirt-10.png',
      longDescription:
        " This inspirational t-shirt features the phrase \"Dream Big\" in bold white letters on a black background. The design is simple yet impactful, reminding wearers of the importance of pursuing their dreams. Made from high-quality material, this t-shirt is perfect for everyday wear or dressing up.",
    }
  ];
  
  export default products;